# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PerryThePenguin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerryThePenguin
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/MLVision'
  pod 'Auth0', '~> 1.0'
  pod 'Lock', '~> 2.0'

end
